### ISSUE TITLE
Consider using search() in s:nextItem

### ISSUE THREAD

**Issue by LemonBoy** [chreekat/vimin#1]
The help file `eval.txt` mentions two flags that might be useful

```
 'n'     do Not move the cursor
 'W'     don't Wrap around the end of the file
```

**Comment by chreekat** [comment]
Cool, I'll look into that this weekend. :)

**Comment by chreekat** [comment]
Ah, I think I did this because you can't specify a _start_ line for search() without moving the cursor. I think it will stay that way. I'll modify the comment, though.

**Comment by chreekat** [comment]
I'll close this, but reopen if you think I'm wrong.

**Comment by LemonBoy** [comment]
Using `cursor` and setting the `'` mark before changing the cursor should do the trick, by using `search` with no `s` flag you can just `m'` when you're done and the code's IMO nicer.

**Comment by chreekat** [comment]
It might look nicer or more concise, but I'd argue it's "nicer" to never
touch or depend on any global state.
